### ISSUE TITLE
error ..

### ISSUE THREAD

**Issue by juanquy** [SvenSommer/darksky2influxdb#1]
Hi, I got this error, but if I type another location like Berlin it works.
===========================================================
`DarkSky data will be written to InfluxDB on cron interval '*/10 * * * *'
/home/sdsadmin/darksky2influxdb/importForecast.js:71
            var daily = forecast.daily;
                                 ^

TypeError: Cannot read property 'daily' of null
    at /home/sdsadmin/darksky2influxdb/importForecast.js:71:34
    at Request._callback (/home/sdsadmin/darksky2influxdb/node_modules/darksky-node/lib/darksky-api.js:34:13)
    at Request.self.callback (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)`
=============================================
So I was thinking it was a location issue but if I run :
https://api.darksky.net/forecast/My KEY was Here /38.4039,-96.1817
It works so the error is not cuz darksky do not provide my location.

any ideas?
regards
JC

**Comment by nfwolfpryde** [comment]
I have the same error, were you ever able to figure out the issue?

**Comment by SvenSommer** [comment]
This will be no issue after darsk sky went offline. Sorry for late response.
